source "https://rubygems.org"

ruby "3.2.0"

gem "bootsnap", require: false
gem "importmap-rails"
gem "jbuilder"
gem "pg"
gem "puma", ">= 5.0"
gem "rails", "~> 7.1.2"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "column_sync", path: "../../../../column_sync"
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.1.0"
end

group :development do
  gem "web-console"
end
