name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} - Postgres ${{ matrix.postgres }}
    strategy:
      matrix:
        ruby:
          - '3.0.5'
          - '3.1.4'
          - '3.2.2'
          - '3.3.0'
        postgres:
          - '14'
          - '15'
          - '16'
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: |
        cd spec/support/dummy/
        bundle install
        cp config/database.yml.github-actions config/database.yml
        rake db:create db:migrate
        rspec
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
